version: "3.7"

services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pgsql
 
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: pgadmin-data
        target: /var/lib/pgadmin
    links:
      - "db:pgsql-server"
    networks:
      - pgsql
    depends_on:
      - db

networks:
  pgsql:
    driver: bridge

volumes:
  db-data:
  pgadmin-data: